/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface AccessTokenResponse {
  /** @nullable */
  accessToken?: string | null;
  expiresIn?: number;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  readonly tokenType?: string | null;
}
