/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface BookModel {
  /** @nullable */
  author?: string | null;
  /** @nullable */
  bookCoverUrl?: string | null;
  /** @nullable */
  description?: string | null;
  id?: string;
  isAddedByUser?: boolean;
  /** @nullable */
  isbn?: string | null;
  isPhotoUploaded?: boolean;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  title?: string | null;
}
