/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export type PostBooksAddBody = {
  Title: string;
  Author: string;
  Description: string;
  Isbn?: string;
  Language: string;
  BookCover?: Blob;
};
