/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface QueueUser {
  /** @nullable */
  lowQualityPhotoUrl?: string | null;
  /** @nullable */
  username: string | null;
}
