/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { QueueUser } from './queueUser';

export interface QueueModel {
  /** @nullable */
  queue?: QueueUser[] | null;
  owner?: QueueUser;
  holder?: QueueUser;
}
