/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { QueueUser } from './queueUser';

export interface QueueModel {
  holder?: QueueUser;
  owner?: QueueUser;
  /** @nullable */
  queue?: QueueUser[] | null;
}
