/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface TwoFactorResponse {
  isMachineRemembered?: boolean;
  isTwoFactorEnabled?: boolean;
  /** @nullable */
  recoveryCodes?: string[] | null;
  recoveryCodesLeft?: number;
  /** @nullable */
  sharedKey?: string | null;
}
