/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export type UserProfileFriendshipStatus = typeof UserProfileFriendshipStatus[keyof typeof UserProfileFriendshipStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileFriendshipStatus = {
  Friend: 'Friend',
  IncomeRequest: 'IncomeRequest',
  OutcomeRequest: 'OutcomeRequest',
  None: 'None',
} as const;
