/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface UserData {
  /** @nullable */
  contactUrl?: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName?: string | null;
  id: string;
  isProfileFilled: boolean;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  username: string | null;
}
