/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface UserProfile {
  /** @nullable */
  contactUrl?: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  highQualityPhotoUrl?: string | null;
  id?: string;
  isFriend?: boolean;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  lowQualityPhotoUrl?: string | null;
  /** @nullable */
  username: string | null;
}
