/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface AccessTokenResponse {
  /** @nullable */
  readonly tokenType?: string | null;
  /** @nullable */
  accessToken: string | null;
  expiresIn: number;
  /** @nullable */
  refreshToken: string | null;
}
