/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface BookModel {
  id?: string;
  title?: string;
  author?: string;
  description?: string;
  /** @nullable */
  bookCoverUrl?: string | null;
  /** @nullable */
  isbn?: string | null;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  publicationYear?: number | null;
  isPhotoUploaded?: boolean;
  isAddedByUser?: boolean;
}
