/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export type FriendshipStatus = typeof FriendshipStatus[keyof typeof FriendshipStatus];

export const FriendshipStatus = {
  Friend: 'Friend',
  IncomeRequest: 'IncomeRequest',
  OutcomeRequest: 'OutcomeRequest',
  None: 'None',
} as const;
