/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { BookModel } from './bookModel';

export interface FriendItemInfo {
  itemId?: string;
  book: BookModel;
  amIHolder?: boolean;
  ownerId?: string;
  /** @nullable */
  holderContact?: string | null;
  /** @nullable */
  holderUsername?: string | null;
  /** @nullable */
  whoToGiveAfterContact?: string | null;
  /** @nullable */
  whoToGiveAfterUserName?: string | null;
  queueNumber?: number;
}
