/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface InfoRequest {
  /** @nullable */
  newEmail?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  oldPassword?: string | null;
}
