/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { BookModel } from './bookModel';
import type { UserInTextProfile } from './userInTextProfile';

export interface ItemInfo {
  itemId: string;
  book: BookModel;
  owner: UserInTextProfile;
  holder: UserInTextProfile;
  firstInQueue?: UserInTextProfile;
  /** @nullable */
  queuePosition?: number | null;
  holderChangedDaysAgo?: number;
}
