/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { BookModel } from './bookModel';

export interface MyItemInfo {
  itemId?: string;
  book?: BookModel;
  currentHolderId?: string;
  /** @nullable */
  currentHolderContact?: string | null;
}
