/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type NotificationBaseFriendTakeBookToReadNotificationType = typeof NotificationBaseFriendTakeBookToReadNotificationType[keyof typeof NotificationBaseFriendTakeBookToReadNotificationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationBaseFriendTakeBookToReadNotificationType = {
  FriendTakeBookToReadNotification: 'FriendTakeBookToReadNotification',
} as const;
