/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseNewBooksInFriendShelfNotificationType } from './notificationBaseNewBooksInFriendShelfNotificationType';
import type { UserProfile } from './userProfile';

export interface NotificationBaseNewBooksInFriendShelfNotification {
  $type: NotificationBaseNewBooksInFriendShelfNotificationType;
  newBooksCoverUrls: string[];
  friendId?: string;
  friend: UserProfile;
  id?: string;
  createdAt?: string;
  isRead?: boolean;
}
