/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseSomeoneQueueToItemNotificationType } from './notificationBaseSomeoneQueueToItemNotificationType';
import type { UserProfile } from './userProfile';
import type { BookModel } from './bookModel';

export interface NotificationBaseSomeoneQueueToItemNotification {
  $type: NotificationBaseSomeoneQueueToItemNotificationType;
  newQueueMember: UserProfile;
  itemId?: string;
  book: BookModel;
  id?: string;
  createdAt?: string;
  isRead?: boolean;
}
