/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseSomeoneBecameHolderOfYourItemNotificationType } from './notificationBaseSomeoneBecameHolderOfYourItemNotificationType';
import type { UserProfile } from './userProfile';
import type { BookModel } from './bookModel';

export interface NotificationBaseSomeoneBecameHolderOfYourItemNotification {
  type: NotificationBaseSomeoneBecameHolderOfYourItemNotificationType;
  newHolder: UserProfile;
  itemId?: string;
  book: BookModel;
  id: string;
  createdAt: string;
  isRead: boolean;
}
