/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseFriendshipStatusChangedNotificationType } from './notificationBaseFriendshipStatusChangedNotificationType';
import type { UserProfile } from './userProfile';
import type { FriendshipStatus } from './friendshipStatus';

export interface NotificationBaseFriendshipStatusChangedNotification {
  $type: NotificationBaseFriendshipStatusChangedNotificationType;
  personId?: string;
  person: UserProfile;
  newStatus?: FriendshipStatus;
  id?: string;
  createdAt?: string;
  isRead?: boolean;
}
