/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseSomeoneBecameHolderOfYourItemNotification } from './notificationBaseSomeoneBecameHolderOfYourItemNotification';
import type { NotificationBaseSomeoneQueueToItemNotification } from './notificationBaseSomeoneQueueToItemNotification';
import type { NotificationBaseYourQueuePositionChangedNotification } from './notificationBaseYourQueuePositionChangedNotification';
import type { NotificationBaseFriendTakeBookToReadNotification } from './notificationBaseFriendTakeBookToReadNotification';
import type { NotificationBaseNewBooksInFriendShelfNotification } from './notificationBaseNewBooksInFriendShelfNotification';
import type { NotificationBaseFriendshipStatusChangedNotification } from './notificationBaseFriendshipStatusChangedNotification';
import type { NotificationBaseReadingProgressReminderNotification } from './notificationBaseReadingProgressReminderNotification';

export type NotificationBase = NotificationBaseSomeoneBecameHolderOfYourItemNotification | NotificationBaseSomeoneQueueToItemNotification | NotificationBaseYourQueuePositionChangedNotification | NotificationBaseFriendTakeBookToReadNotification | NotificationBaseNewBooksInFriendShelfNotification | NotificationBaseFriendshipStatusChangedNotification | NotificationBaseReadingProgressReminderNotification;
