/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type NotificationBaseNewBooksInFriendShelfNotificationType = typeof NotificationBaseNewBooksInFriendShelfNotificationType[keyof typeof NotificationBaseNewBooksInFriendShelfNotificationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationBaseNewBooksInFriendShelfNotificationType = {
  NewBooksInFriendShelf: 'NewBooksInFriendShelf',
} as const;
