/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseFriendTakeBookToReadNotificationType } from './notificationBaseFriendTakeBookToReadNotificationType';
import type { BookModel } from './bookModel';
import type { UserProfile } from './userProfile';

export interface NotificationBaseFriendTakeBookToReadNotification {
  type: NotificationBaseFriendTakeBookToReadNotificationType;
  book: BookModel;
  friendId?: string;
  friend: UserProfile;
  id: string;
  createdAt: string;
  isRead: boolean;
}
