/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type NotificationBaseYourQueuePositionChangedNotificationType = typeof NotificationBaseYourQueuePositionChangedNotificationType[keyof typeof NotificationBaseYourQueuePositionChangedNotificationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationBaseYourQueuePositionChangedNotificationType = {
  YourQueuePositionChangedNotification: 'YourQueuePositionChangedNotification',
} as const;
