/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseYourQueuePositionChangedNotificationType } from './notificationBaseYourQueuePositionChangedNotificationType';
import type { BookModel } from './bookModel';

export interface NotificationBaseYourQueuePositionChangedNotification {
  $type: NotificationBaseYourQueuePositionChangedNotificationType;
  newPosition?: number;
  itemId?: string;
  bookId?: string;
  book: BookModel;
  id?: string;
  createdAt?: string;
  isRead?: boolean;
}
