/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationBaseReadingProgressReminderNotificationType } from './notificationBaseReadingProgressReminderNotificationType';
import type { BookModel } from './bookModel';

export interface NotificationBaseReadingProgressReminderNotification {
  type: NotificationBaseReadingProgressReminderNotificationType;
  readingDays: number;
  itemId?: string;
  book: BookModel;
  id: string;
  createdAt: string;
  isRead: boolean;
}
