/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type PostUsersEditProfileBody = {
  FirstName?: string;
  LastName?: string;
  Username?: string;
  ContactUrl?: string;
  PhotoFile?: IFormFile;
};
