/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export type PostUsersEditProfileBody = {
  FirstName?: string;
  LastName?: string;
  Username?: string;
  ContactUrl?: string;
  PhotoFile?: Blob;
};
