/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type PostBooksAddBody = {
  Title?: string;
  Author?: string;
  Description?: string;
  Isbn?: string;
  Language?: string;
  PublicationYear?: number;
  BookCover?: IFormFile;
};
