/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export type PostAuthLoginParams = {
  useCookies?: boolean;
  useSessionCookies?: boolean;
};
