/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { QueueUser } from './queueUser';
import type { UserProfile } from './userProfile';

export interface QueueModel {
  itemId?: string;
  /** @nullable */
  queue?: QueueUser[] | null;
  owner?: UserProfile;
  holder?: UserProfile;
}
