/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface RegisterRequest {
  /** @nullable */
  email: string | null;
  /** @nullable */
  password: string | null;
}
