/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface ResetPasswordRequest {
  /** @nullable */
  email: string | null;
  /** @nullable */
  resetCode: string | null;
  /** @nullable */
  newPassword: string | null;
}
