/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ResetPasswordRequest {
  email: string;
  resetCode: string;
  newPassword: string;
}
