/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface TwoFactorRequest {
  /** @nullable */
  enable?: boolean | null;
  /** @nullable */
  twoFactorCode?: string | null;
  resetSharedKey?: boolean;
  resetRecoveryCodes?: boolean;
  forgetMachine?: boolean;
}
