/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface TwoFactorResponse {
  /** @nullable */
  sharedKey: string | null;
  recoveryCodesLeft: number;
  /** @nullable */
  recoveryCodes?: string[] | null;
  isTwoFactorEnabled: boolean;
  isMachineRemembered: boolean;
}
