/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BS.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FriendshipStatus } from './friendshipStatus';

export interface UserProfile {
  friendshipStatus?: FriendshipStatus;
  id?: string;
  username: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  contactUrl?: string | null;
  /** @nullable */
  highQualityPhotoUrl?: string | null;
  /** @nullable */
  lowQualityPhotoUrl?: string | null;
}
