/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import type { ValidationProblemDetailsErrors } from './validationProblemDetailsErrors';

export interface ValidationProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  errors?: ValidationProblemDetailsErrors;
  [key: string]: unknown;
}
