/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type ValidationProblemDetailsErrors = {[key: string]: string[]} | null;
