/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  PostQueueItemIdEnqueueParams,
  QueueModel
} from '.././model'
import { api } from '../../services/api';
import type { ErrorType } from '../../services/api';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export const getQueueItemIdGetQueue = (
    itemId: string,
 options?: SecondParameter<typeof api>,signal?: AbortSignal
) => {
      
      
      return api<QueueModel>(
      {url: `/Queue/${itemId}/getQueue`, method: 'GET', signal
    },
      options);
    }
  

export const getGetQueueItemIdGetQueueQueryKey = (itemId: string,) => {
    return [`/Queue/${itemId}/getQueue`] as const;
    }

    
export const getGetQueueItemIdGetQueueQueryOptions = <TData = Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError = ErrorType<unknown>>(itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueueItemIdGetQueueQueryKey(itemId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>> = ({ signal }) => getQueueItemIdGetQueue(itemId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(itemId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQueueItemIdGetQueueQueryResult = NonNullable<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>>
export type GetQueueItemIdGetQueueQueryError = ErrorType<unknown>


export function useGetQueueItemIdGetQueue<TData = Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError = ErrorType<unknown>>(
 itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueueItemIdGetQueue>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQueueItemIdGetQueue<TData = Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError = ErrorType<unknown>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueueItemIdGetQueue>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQueueItemIdGetQueue<TData = Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError = ErrorType<unknown>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData>>, request?: SecondParameter<typeof api>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetQueueItemIdGetQueue<TData = Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError = ErrorType<unknown>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueueItemIdGetQueue>>, TError, TData>>, request?: SecondParameter<typeof api>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQueueItemIdGetQueueQueryOptions(itemId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const postQueueItemIdEnqueue = (
    itemId: string,
    params?: PostQueueItemIdEnqueueParams,
 options?: SecondParameter<typeof api>,signal?: AbortSignal
) => {
      
      
      return api<void>(
      {url: `/Queue/${itemId}/enqueue`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getPostQueueItemIdEnqueueMutationOptions = <TData = Awaited<ReturnType<typeof postQueueItemIdEnqueue>>, TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{itemId: string;params?: PostQueueItemIdEnqueueParams}, TContext>, request?: SecondParameter<typeof api>}
) => {
const mutationKey = ['postQueueItemIdEnqueue'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQueueItemIdEnqueue>>, {itemId: string;params?: PostQueueItemIdEnqueueParams}> = (props) => {
          const {itemId,params} = props ?? {};

          return  postQueueItemIdEnqueue(itemId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{itemId: string;params?: PostQueueItemIdEnqueueParams}, TContext>}

    export type PostQueueItemIdEnqueueMutationResult = NonNullable<Awaited<ReturnType<typeof postQueueItemIdEnqueue>>>
    
    export type PostQueueItemIdEnqueueMutationError = ErrorType<unknown>

    export const usePostQueueItemIdEnqueue = <TData = Awaited<ReturnType<typeof postQueueItemIdEnqueue>>, TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{itemId: string;params?: PostQueueItemIdEnqueueParams}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationResult<
        TData,
        TError,
        {itemId: string;params?: PostQueueItemIdEnqueueParams},
        TContext
      > => {

      const mutationOptions = getPostQueueItemIdEnqueueMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const postQueueItemIdLeaveQueue = (
    itemId: string,
 options?: SecondParameter<typeof api>,signal?: AbortSignal
) => {
      
      
      return api<void>(
      {url: `/Queue/${itemId}/leaveQueue`, method: 'POST', signal
    },
      options);
    }
  


export const getPostQueueItemIdLeaveQueueMutationOptions = <TData = Awaited<ReturnType<typeof postQueueItemIdLeaveQueue>>, TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof api>}
) => {
const mutationKey = ['postQueueItemIdLeaveQueue'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQueueItemIdLeaveQueue>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  postQueueItemIdLeaveQueue(itemId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{itemId: string}, TContext>}

    export type PostQueueItemIdLeaveQueueMutationResult = NonNullable<Awaited<ReturnType<typeof postQueueItemIdLeaveQueue>>>
    
    export type PostQueueItemIdLeaveQueueMutationError = ErrorType<unknown>

    export const usePostQueueItemIdLeaveQueue = <TData = Awaited<ReturnType<typeof postQueueItemIdLeaveQueue>>, TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationResult<
        TData,
        TError,
        {itemId: string},
        TContext
      > => {

      const mutationOptions = getPostQueueItemIdLeaveQueueMutationOptions(options);

      return useMutation(mutationOptions);
    }
    