/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */

export interface ResetPasswordRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  resetCode?: string | null;
}
