apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - api.staging.book-sharing.local
      secretName: bs-tls-secret
  rules:
    - host: api.staging.book-sharing.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-bs-api
                port:
                  number: 443
