/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BookSharingApi
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BookModel,
  PostApiBooksAddBody,
  PostApiBooksAddParams
} from '.././model'



export const getApiBooksSearchByIdBookId = (
    bookId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BookModel>> => {
    
    return axios.default.get(
      `/api/Books/searchById/${bookId}`,options
    );
  }


export const getGetApiBooksSearchByIdBookIdQueryKey = (bookId: string,) => {
    return [`/api/Books/searchById/${bookId}`] as const;
    }

    
export const getGetApiBooksSearchByIdBookIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError = AxiosError<unknown>>(bookId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBooksSearchByIdBookIdQueryKey(bookId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>> = ({ signal }) => getApiBooksSearchByIdBookId(bookId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(bookId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiBooksSearchByIdBookIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>>
export type GetApiBooksSearchByIdBookIdQueryError = AxiosError<unknown>


export function useGetApiBooksSearchByIdBookId<TData = Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError = AxiosError<unknown>>(
 bookId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByIdBookId<TData = Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError = AxiosError<unknown>>(
 bookId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByIdBookId<TData = Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError = AxiosError<unknown>>(
 bookId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiBooksSearchByIdBookId<TData = Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError = AxiosError<unknown>>(
 bookId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIdBookId>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiBooksSearchByIdBookIdQueryOptions(bookId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getApiBooksSearchByTitleTitle = (
    title: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BookModel>> => {
    
    return axios.default.get(
      `/api/Books/searchByTitle/${title}`,options
    );
  }


export const getGetApiBooksSearchByTitleTitleQueryKey = (title: string,) => {
    return [`/api/Books/searchByTitle/${title}`] as const;
    }

    
export const getGetApiBooksSearchByTitleTitleQueryOptions = <TData = Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError = AxiosError<unknown>>(title: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBooksSearchByTitleTitleQueryKey(title);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>> = ({ signal }) => getApiBooksSearchByTitleTitle(title, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(title), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiBooksSearchByTitleTitleQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>>
export type GetApiBooksSearchByTitleTitleQueryError = AxiosError<unknown>


export function useGetApiBooksSearchByTitleTitle<TData = Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError = AxiosError<unknown>>(
 title: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByTitleTitle<TData = Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError = AxiosError<unknown>>(
 title: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByTitleTitle<TData = Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError = AxiosError<unknown>>(
 title: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiBooksSearchByTitleTitle<TData = Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError = AxiosError<unknown>>(
 title: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByTitleTitle>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiBooksSearchByTitleTitleQueryOptions(title,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getApiBooksSearchByIsbnIsbn = (
    isbn: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BookModel>> => {
    
    return axios.default.get(
      `/api/Books/searchByIsbn/${isbn}`,options
    );
  }


export const getGetApiBooksSearchByIsbnIsbnQueryKey = (isbn: string,) => {
    return [`/api/Books/searchByIsbn/${isbn}`] as const;
    }

    
export const getGetApiBooksSearchByIsbnIsbnQueryOptions = <TData = Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError = AxiosError<unknown>>(isbn: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBooksSearchByIsbnIsbnQueryKey(isbn);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>> = ({ signal }) => getApiBooksSearchByIsbnIsbn(isbn, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(isbn), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiBooksSearchByIsbnIsbnQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>>
export type GetApiBooksSearchByIsbnIsbnQueryError = AxiosError<unknown>


export function useGetApiBooksSearchByIsbnIsbn<TData = Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError = AxiosError<unknown>>(
 isbn: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByIsbnIsbn<TData = Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError = AxiosError<unknown>>(
 isbn: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiBooksSearchByIsbnIsbn<TData = Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError = AxiosError<unknown>>(
 isbn: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiBooksSearchByIsbnIsbn<TData = Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError = AxiosError<unknown>>(
 isbn: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBooksSearchByIsbnIsbn>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiBooksSearchByIsbnIsbnQueryOptions(isbn,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const postApiBooksAdd = (
    postApiBooksAddBody: PostApiBooksAddBody,
    params?: PostApiBooksAddParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BookModel>> => {const formData = new FormData();
if(postApiBooksAddBody.BookCover !== undefined) {
 formData.append('BookCover', postApiBooksAddBody.BookCover)
 }

    
    return axios.default.post(
      `/api/Books/add`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPostApiBooksAddMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBooksAdd>>, TError,{data: PostApiBooksAddBody;params?: PostApiBooksAddParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBooksAdd>>, TError,{data: PostApiBooksAddBody;params?: PostApiBooksAddParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBooksAdd>>, {data: PostApiBooksAddBody;params?: PostApiBooksAddParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postApiBooksAdd(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiBooksAddMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBooksAdd>>>
    export type PostApiBooksAddMutationBody = PostApiBooksAddBody
    export type PostApiBooksAddMutationError = AxiosError<unknown>

    export const usePostApiBooksAdd = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBooksAdd>>, TError,{data: PostApiBooksAddBody;params?: PostApiBooksAddParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof postApiBooksAdd>>,
        TError,
        {data: PostApiBooksAddBody;params?: PostApiBooksAddParams},
        TContext
      > => {

      const mutationOptions = getPostApiBooksAddMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const deleteApiBooksDeleteBookId = (
    bookId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.default.delete(
      `/api/Books/delete/${bookId}`,options
    );
  }



export const getDeleteApiBooksDeleteBookIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>, TError,{bookId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>, TError,{bookId: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>, {bookId: string}> = (props) => {
          const {bookId} = props ?? {};

          return  deleteApiBooksDeleteBookId(bookId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiBooksDeleteBookIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>>
    
    export type DeleteApiBooksDeleteBookIdMutationError = AxiosError<unknown>

    export const useDeleteApiBooksDeleteBookId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>, TError,{bookId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiBooksDeleteBookId>>,
        TError,
        {bookId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiBooksDeleteBookIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    